# Drone CI File!

kind: pipeline
type: kubernetes
name: default

metadata:
  namespace: builds

node_selector:
  doks.digitalocean.com/node-pool: josa-cloud-np

steps:
  - name: build
    image: plugins/docker
    settings:
      repo: josaorg/portal-web
      build_args:
        [
          PORTAL_API_URL=https://portal.api.prod.josa.ngo/,
          ASSETS_BUCKET_URL=https://josa-api.fra1.digitaloceanspaces.com/portal,
          OTS_API_URL=https://ots.josa.ngo/api/v1/,
          MATOMO_SITE_ID=2,
        ]
      tags:
        - ${DRONE_COMMIT_SHA}
        - stable
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
  - name: notify
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: heartbeat
    depends_on:
      - build
