version: '3.8'

services:
  nuxt-app:
    build:
      context: .
    container_name: portal-web
    restart: unless-stopped
    environment:
      PORTAL_API_URL: #add api url
      ASSETS_BUCKET_URL: #add bucket url
    ports:
      - 3000:3000
    command: 'npm run start'
    networks:
      - nuxt-network

  web-server:
    image: nginx:stable-alpine
    container_name: web-server
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf
      - web-root:/var/www/josa
    ports:
      - 80:80
    networks:
      - nuxt-network
    depends_on:
      - nuxt-app
    restart: unless-stopped

volumes:
  web-root:


networks:
  nuxt-network:
    driver: bridge
