version: '3.8'

services:
nuxt-app:
  build: ./portal-web
  container_name: portal-web
  restart: always
  ports:
    - '3000:3000'
  command: 'npm run start'
  networks:
    - nuxt-network
networks:
  nuxt-network:
    driver: bridge
